/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package parser;

import com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException;
import java.awt.EventQueue;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author Marcin
 */
public class MatchOdds extends javax.swing.JPanel {

    /**
     * Creates new form MatchOdds
     */
    private XMLParser parser = null;
    private String urlString = null;
    
    private String matchResult = null;
    private String doubleChance = null;
    private String underOver = null;
    
    private PhraseSearcher phraseSearcher = null;
    
    public MatchOdds()
    {
        initComponents();
        phraseSearcher = new PhraseSearcher(jLabelStatus, jTextAreaOdds, jTextFieldPhrase);
        setFields();
    }
    
    private void setFields()
    {    
        jRadioButtonMatchResult.setText("Match Result");
        jRadioButtonDoubleChance.setText("Double Chance");
        jRadioButtonOverUnder.setText("Under/Over");
        jRadioButtonMatchResult.setSelected(true);
        jButtonRefresh.setText("Get Odds");
        jButtonNextOccurence.setText("Next occurence");
        jLabelStatus.setText("");
        jLabel1.setText("Phrase to search:");
        
        matchResult = "http://whdn.williamhill.com/pricefeed/openbet_cdn?action=template&template=getHierarchyByMarketType&classId=46&marketSort=MR&filterBIR=N";
        doubleChance = "http://whdn.williamhill.com/pricefeed/openbet_cdn?action=template&template=getHierarchyByMarketType&classId=46&marketSort=DC&filterBIR=N";
        underOver = "http://whdn.williamhill.com/pricefeed/openbet_cdn?action=template&template=getHierarchyByMarketType&classId=46&marketSort=HL&filterBIR=N";
     
        urlString = matchResult;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupChoice = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOdds = new javax.swing.JTextArea();
        jButtonRefresh = new javax.swing.JButton();
        jRadioButtonMatchResult = new javax.swing.JRadioButton();
        jRadioButtonDoubleChance = new javax.swing.JRadioButton();
        jRadioButtonOverUnder = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldPhrase = new javax.swing.JTextField();
        jButtonNextOccurence = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();

        jTextAreaOdds.setColumns(20);
        jTextAreaOdds.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOdds);

        jButtonRefresh.setText("jButton1");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        buttonGroupChoice.add(jRadioButtonMatchResult);
        jRadioButtonMatchResult.setText("jRadioButton1");
        jRadioButtonMatchResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMatchResultActionPerformed(evt);
            }
        });

        buttonGroupChoice.add(jRadioButtonDoubleChance);
        jRadioButtonDoubleChance.setText("jRadioButton2");
        jRadioButtonDoubleChance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDoubleChanceActionPerformed(evt);
            }
        });

        buttonGroupChoice.add(jRadioButtonOverUnder);
        jRadioButtonOverUnder.setText("jRadioButton3");
        jRadioButtonOverUnder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOverUnderActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jButtonNextOccurence.setText("jButton1");
        jButtonNextOccurence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextOccurenceActionPerformed(evt);
            }
        });

        jLabelStatus.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMatchResult)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonDoubleChance)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonOverUnder))
                            .addComponent(jLabelStatus)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNextOccurence)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefresh)
                    .addComponent(jRadioButtonMatchResult)
                    .addComponent(jRadioButtonDoubleChance)
                    .addComponent(jRadioButtonOverUnder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonNextOccurence)
                    .addComponent(jTextFieldPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatus))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() 
            {
                try 
                {
                    jTextAreaOdds.setText("");
                    parser = new XMLParser(jTextAreaOdds, urlString);
                    parser.parse();
                } 
                catch (ParserConfigurationException ex) 
                {
                    Logger.getLogger(MatchOdds.class.getName()).log(Level.SEVERE, null, ex);
                    jTextAreaOdds.setText("Service unavailable, please try later.");
                } 
                catch (SAXException ex) 
                {
                    Logger.getLogger(MatchOdds.class.getName()).log(Level.SEVERE, null, ex);
                    jTextAreaOdds.setText("Service unavailable, please try later.");
                } 
                catch (IOException ex) 
                {
                    Logger.getLogger(MatchOdds.class.getName()).log(Level.SEVERE, null, ex);
                    jTextAreaOdds.setText("Service unavailable, please try later.");
                } 
            }
        });
 
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jRadioButtonMatchResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMatchResultActionPerformed
        
        urlString = matchResult;
    }//GEN-LAST:event_jRadioButtonMatchResultActionPerformed

    private void jRadioButtonDoubleChanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDoubleChanceActionPerformed
        
        urlString = doubleChance;
    }//GEN-LAST:event_jRadioButtonDoubleChanceActionPerformed

    private void jRadioButtonOverUnderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOverUnderActionPerformed
       
        urlString = underOver;
    }//GEN-LAST:event_jRadioButtonOverUnderActionPerformed

    private void jButtonNextOccurenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextOccurenceActionPerformed
        
        phraseSearcher.searchNext();
    }//GEN-LAST:event_jButtonNextOccurenceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupChoice;
    private javax.swing.JButton jButtonNextOccurence;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JRadioButton jRadioButtonDoubleChance;
    private javax.swing.JRadioButton jRadioButtonMatchResult;
    private javax.swing.JRadioButton jRadioButtonOverUnder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOdds;
    private javax.swing.JTextField jTextFieldPhrase;
    // End of variables declaration//GEN-END:variables
}
