/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dataBase;


/**
 *
 * @author Marcin
 */
public class DeleteProgression extends javax.swing.JPanel {

    private int option = 1;
    /**
     * Creates new form DeleteProgression
     */
    public DeleteProgression() {
        initComponents();
        setFields();
    }
    
    private void setFields()
    {
        jButtonDelete.setText("Delete");
        jRadioButtonDeleteAll.setText("Delete progression with bets");
        jRadioButtonDeleteOnlyProg.setText("Delete progression and make "
                + "included bets - bets not in progression");
        jRadioButtonDeleteAll.setSelected(true);
        jLabelInformation.setText("Choose deletion option.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDelete = new javax.swing.ButtonGroup();
        jButtonDelete = new javax.swing.JButton();
        jRadioButtonDeleteAll = new javax.swing.JRadioButton();
        jRadioButtonDeleteOnlyProg = new javax.swing.JRadioButton();
        jLabelInformation = new javax.swing.JLabel();

        jButtonDelete.setText("jButton1");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        buttonGroupDelete.add(jRadioButtonDeleteAll);
        jRadioButtonDeleteAll.setText("jRadioButton1");
        jRadioButtonDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDeleteAllActionPerformed(evt);
            }
        });

        buttonGroupDelete.add(jRadioButtonDeleteOnlyProg);
        jRadioButtonDeleteOnlyProg.setText("jRadioButton2");
        jRadioButtonDeleteOnlyProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDeleteOnlyProgActionPerformed(evt);
            }
        });

        jLabelInformation.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInformation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(jButtonDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDeleteOnlyProg)
                            .addComponent(jRadioButtonDeleteAll))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonDelete)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonDeleteAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDeleteOnlyProg)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelInformation)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDeleteAllActionPerformed
        
        option = 1;
    }//GEN-LAST:event_jRadioButtonDeleteAllActionPerformed

    private void jRadioButtonDeleteOnlyProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDeleteOnlyProgActionPerformed
        
        option = 2;
    }//GEN-LAST:event_jRadioButtonDeleteOnlyProgActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        
        if(option == 1)
            DataContainer.dataFromDB.getQueryManager().deleteProgressionWithBets(DataContainer.id);
        
        if(option == 2)
            DataContainer.dataFromDB.getQueryManager().deleteProgMakeBetsNotInProg(DataContainer.id);
        
        DataContainer.updateLists();
        jLabelInformation.setText("Progression deleted.");
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDelete;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JLabel jLabelInformation;
    private javax.swing.JRadioButton jRadioButtonDeleteAll;
    private javax.swing.JRadioButton jRadioButtonDeleteOnlyProg;
    // End of variables declaration//GEN-END:variables
}
