/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dataBase;

/**
 *
 * @author Marcin
 */
public class EditProgression extends javax.swing.JPanel {

    /**
     * Creates new form EditProgression
     */
    private int status = 0;
    
    public EditProgression() {
        initComponents();
        setFields();
        loadData();
    }
    
    private void setFields()
    {
        jRadioButtonActive.setText("Active");
        jRadioButtonResolved.setText("Resolved");
        jButtonSave.setText("Save changes");
        jLabel1.setText("Progression name:");
        jTextAreaProgInfo.setEnabled(false);
        jLabelInformation.setText("Edit progression information.");
    }
    
    private void loadData()
    {
        Progression prog = DataContainer.dataFromDB.getQueryManager().getProgression(DataContainer.id);
        jTextFieldProgName.setText(prog.getProgressionName());
        
        //String info = DataContainer.dataFromDB.getQueryManager().viewProgressionInfo(DataContainer.id);
        //double balance = DataContainer.dataFromDB.getQueryManager().viewResolvedProgressionBalance(DataContainer.id);
        jTextAreaProgInfo.setText(getProgressionInfoForTextArea(prog));
    
        setStatus(prog);
    }
    
    private String getProgressionInfoForTextArea(Progression prog)
    {
        String info = DataContainer.dataFromDB.viewProgressionInfo(prog);
        info += DataContainer.dataFromDB.viewProgressionBallance(prog);
        return info;
    }
    
    private void setStatus(Progression prog)
    {
        if(prog.getProgressionStatus() == 1)
            jRadioButtonActive.setSelected(true);
        
        if(prog.getProgressionStatus() == 2)
            jRadioButtonResolved.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupProg = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProgInfo = new javax.swing.JTextArea();
        jRadioButtonActive = new javax.swing.JRadioButton();
        jRadioButtonResolved = new javax.swing.JRadioButton();
        jButtonSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProgName = new javax.swing.JTextField();
        jLabelInformation = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(350, 220));

        jTextAreaProgInfo.setColumns(20);
        jTextAreaProgInfo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProgInfo);

        buttonGroupProg.add(jRadioButtonActive);
        jRadioButtonActive.setText("jRadioButton1");
        jRadioButtonActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonActiveActionPerformed(evt);
            }
        });

        buttonGroupProg.add(jRadioButtonResolved);
        jRadioButtonResolved.setText("jRadioButton1");
        jRadioButtonResolved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonResolvedActionPerformed(evt);
            }
        });

        jButtonSave.setText("jButton1");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabelInformation.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonActive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonResolved)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButtonSave))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProgName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInformation)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldProgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonActive)
                    .addComponent(jRadioButtonResolved)
                    .addComponent(jButtonSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelInformation)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonActiveActionPerformed
        
        status = 1;
    }//GEN-LAST:event_jRadioButtonActiveActionPerformed

    private void jRadioButtonResolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonResolvedActionPerformed
        
        status = 2;
    }//GEN-LAST:event_jRadioButtonResolvedActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        String progressionName = jTextFieldProgName.getText();
        DataContainer.dataFromDB.getQueryManager().updateProgression(progressionName, status, DataContainer.id);
        DataContainer.updateLists();
        jLabelInformation.setText("Progression updated.");
    }//GEN-LAST:event_jButtonSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupProg;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInformation;
    private javax.swing.JRadioButton jRadioButtonActive;
    private javax.swing.JRadioButton jRadioButtonResolved;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaProgInfo;
    private javax.swing.JTextField jTextFieldProgName;
    // End of variables declaration//GEN-END:variables
}
