/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dataBase;

import java.sql.SQLException;

/**
 *
 * @author Marcin
 */
public class EditBet extends javax.swing.JPanel {
   
    private int status = 0;
    private Calendar calendar = null;
    private Bet betNotInProg = null;
    private BetInProgression betInProg = null;
    
    public EditBet() {
        
        initComponents();
        calendar = new Calendar(jComboBoxDay, jComboBoxMonth, jComboBoxYear, jComboBoxHour, jComboBoxMinute);
        setFields();
        loadData();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupProgression = new javax.swing.ButtonGroup();
        buttonGroupStatus = new javax.swing.ButtonGroup();
        jPanelEditBet = new javax.swing.JPanel();
        jTextFieldOdd = new javax.swing.JTextField();
        jLabelTime = new javax.swing.JLabel();
        jComboBoxMinute = new javax.swing.JComboBox();
        jLabelBetName = new javax.swing.JLabel();
        jLabelNote = new javax.swing.JLabel();
        jButtonSaveChanges = new javax.swing.JButton();
        jLabelBukmacher = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jTextFieldBetName = new javax.swing.JTextField();
        jComboBoxMonth = new javax.swing.JComboBox();
        jCheckBoxProgression = new javax.swing.JCheckBox();
        jTextFieldStake = new javax.swing.JTextField();
        jLabelType = new javax.swing.JLabel();
        jComboBoxBukmacher = new javax.swing.JComboBox();
        jComboBoxYear = new javax.swing.JComboBox();
        jLabelStake = new javax.swing.JLabel();
        jComboBoxType = new javax.swing.JComboBox();
        jComboBoxDay = new javax.swing.JComboBox();
        jLabelOdd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNote = new javax.swing.JTextArea();
        jComboBoxHour = new javax.swing.JComboBox();
        jLabelTitle = new javax.swing.JLabel();
        jPanelProgression = new javax.swing.JPanel();
        jRadioButtonNewProgression = new javax.swing.JRadioButton();
        jRadioButtonExistingProgression = new javax.swing.JRadioButton();
        jLabelNewProgressionName = new javax.swing.JLabel();
        jComboBoxExistingProgression = new javax.swing.JComboBox();
        jTextFieldProgressionName = new javax.swing.JTextField();
        jLabelProgressionBalance = new javax.swing.JLabel();
        jRadioButtonWon = new javax.swing.JRadioButton();
        jRadioButtonLost = new javax.swing.JRadioButton();
        jRadioButtonUnresolved = new javax.swing.JRadioButton();

        jLabelTime.setText("jLabel1");

        jLabelBetName.setText("jLabel1");

        jLabelNote.setText("jLabel1");

        jButtonSaveChanges.setText("jButton1");
        jButtonSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveChangesActionPerformed(evt);
            }
        });

        jLabelBukmacher.setText("jLabel1");

        jLabelDate.setText("jLabel1");

        jCheckBoxProgression.setText("jCheckBox1");
        jCheckBoxProgression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProgressionActionPerformed(evt);
            }
        });

        jLabelType.setText("jLabel1");

        jLabelStake.setText("jLabel1");

        jLabelOdd.setText("jLabel1");

        jTextAreaNote.setColumns(20);
        jTextAreaNote.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNote);

        jLabelTitle.setText("jLabel1");

        buttonGroupProgression.add(jRadioButtonNewProgression);
        jRadioButtonNewProgression.setText("jRadioButton1");
        jRadioButtonNewProgression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNewProgressionActionPerformed(evt);
            }
        });

        buttonGroupProgression.add(jRadioButtonExistingProgression);
        jRadioButtonExistingProgression.setText("jRadioButton2");
        jRadioButtonExistingProgression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonExistingProgressionActionPerformed(evt);
            }
        });

        jLabelNewProgressionName.setText("jLabel1");

        jComboBoxExistingProgression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxExistingProgressionActionPerformed(evt);
            }
        });

        jLabelProgressionBalance.setText("jLabel1");

        javax.swing.GroupLayout jPanelProgressionLayout = new javax.swing.GroupLayout(jPanelProgression);
        jPanelProgression.setLayout(jPanelProgressionLayout);
        jPanelProgressionLayout.setHorizontalGroup(
            jPanelProgressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressionLayout.createSequentialGroup()
                .addGroup(jPanelProgressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProgressionLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jComboBoxExistingProgression, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProgressionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelProgressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonNewProgression)
                            .addComponent(jRadioButtonExistingProgression))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProgressionName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProgressionLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelNewProgressionName)))
                .addContainerGap(48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelProgressionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProgressionBalance)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanelProgressionLayout.setVerticalGroup(
            jPanelProgressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonNewProgression)
                .addGap(2, 2, 2)
                .addGroup(jPanelProgressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNewProgressionName)
                    .addComponent(jTextFieldProgressionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jRadioButtonExistingProgression)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxExistingProgression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabelProgressionBalance))
        );

        buttonGroupStatus.add(jRadioButtonWon);
        jRadioButtonWon.setText("jRadioButton1");
        jRadioButtonWon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWonActionPerformed(evt);
            }
        });

        buttonGroupStatus.add(jRadioButtonLost);
        jRadioButtonLost.setText("jRadioButton2");
        jRadioButtonLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLostActionPerformed(evt);
            }
        });

        buttonGroupStatus.add(jRadioButtonUnresolved);
        jRadioButtonUnresolved.setText("jRadioButton4");
        jRadioButtonUnresolved.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUnresolvedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditBetLayout = new javax.swing.GroupLayout(jPanelEditBet);
        jPanelEditBet.setLayout(jPanelEditBetLayout);
        jPanelEditBetLayout.setHorizontalGroup(
            jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditBetLayout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonUnresolved)
                    .addComponent(jRadioButtonLost)
                    .addComponent(jRadioButtonWon)
                    .addComponent(jButtonSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEditBetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelTitle)
                        .addGroup(jPanelEditBetLayout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelEditBetLayout.createSequentialGroup()
                                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelBetName)
                                        .addComponent(jLabelOdd)
                                        .addComponent(jLabelStake)
                                        .addComponent(jLabelDate)
                                        .addComponent(jLabelBukmacher)
                                        .addComponent(jLabelNote)
                                        .addComponent(jLabelTime)
                                        .addComponent(jLabelType))
                                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelEditBetLayout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane1)
                                                .addComponent(jComboBoxBukmacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanelEditBetLayout.createSequentialGroup()
                                            .addGap(44, 44, 44)
                                            .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldOdd)
                                                    .addComponent(jTextFieldStake, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jTextFieldBetName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanelEditBetLayout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelEditBetLayout.createSequentialGroup()
                                                    .addComponent(jComboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jComboBoxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanelEditBetLayout.createSequentialGroup()
                                                    .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(jCheckBoxProgression)))
                        .addGroup(jPanelEditBetLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addComponent(jPanelProgression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(100, Short.MAX_VALUE)))
        );
        jPanelEditBetLayout.setVerticalGroup(
            jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditBetLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButtonSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonWon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonUnresolved)
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelEditBetLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelTitle)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBetName)
                        .addComponent(jTextFieldBetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDate)
                        .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTime)
                        .addComponent(jComboBoxHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelType)
                        .addComponent(jComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelOdd, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldOdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelStake, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldStake, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelBukmacher, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboBoxBukmacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelEditBetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNote))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jCheckBoxProgression)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanelProgression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelEditBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelEditBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadData()
    {
        //load zalezy od wybranej listy 
        if(DataContainer.listName.equals("Active bets in progressions")
               || DataContainer.listName.equals("Won bets in progressions")
               || DataContainer.listName.equals("Lost bets in progressions")
               || DataContainer.listName.equals("Resolved bets in progressions"))
             loadDataFromDBforBetInProg();
              
        if(DataContainer.listName.equals("Active bets not in progressions")
                || DataContainer.listName.equals("Won bets not in progressions")
                || DataContainer.listName.equals("Lost bets not in progressions")
                || DataContainer.listName.equals("Resolved bets not in progressions"))
            loadDataFromDBforBet();
    }
    
    private void setFields()
    {
        jLabelTitle.setText("Set information for new bet");
        jLabelBetName.setText("Bet name:");
        jLabelStake.setText("Stake:");
        jLabelOdd.setText("Odd:");
        jLabelDate.setText("Date of event:");
        jLabelTime.setText("Start time:");
        jLabelBukmacher.setText("Bukmacher:");
        jLabelNote.setText("Note:");
        jLabelType.setText("Type:");
        jCheckBoxProgression.setText("is part of progression");
        jPanelProgression.setVisible(false);
        jButtonSaveChanges.setText("Save changes");
        jLabelProgressionBalance.setText("");
        
        jRadioButtonWon.setText("Won");
        jRadioButtonLost.setText("Lost");
        jRadioButtonUnresolved.setText("Unresolved");
              
        jRadioButtonNewProgression.setText("New progression");
        jRadioButtonExistingProgression.setText("Existing progression");
        buttonGroupProgression.add(jRadioButtonExistingProgression);
        buttonGroupProgression.add(jRadioButtonNewProgression);
        
        jLabelNewProgressionName.setText("Progression name:");
        jRadioButtonExistingProgression.setSelected(true);
        jTextFieldProgressionName.setEnabled(false);
        jComboBoxExistingProgression.setEnabled(true);
        
        //na liste wczytywane sa wszystkie progresje - lacznie z zakonczonymi
        jComboBoxExistingProgression.setModel(DataContainer.comboBoxModelAllProgressions); 
        viewProgressionBalanceInLabel();
        fillComboBoxBukmacher();
        fillComboBoxType();
        calendar.fillComboBoxDateTime();
    }
    
    private void fillComboBoxType()
    {
        jComboBoxType.addItem("1");
        jComboBoxType.addItem("x");
        jComboBoxType.addItem("2");
        jComboBoxType.addItem("1x");
        jComboBoxType.addItem("12");
        jComboBoxType.addItem("x2");
        jComboBoxType.addItem("over 2.5");
        jComboBoxType.addItem("under 2.5");
        jComboBoxType.addItem("other");
    }
    
    private void fillComboBoxBukmacher()
    {
        for(BukmacherENUM b : BukmacherENUM.values())
            jComboBoxBukmacher.addItem(b);
    }
    
    private void loadDataFromDBforBet()
    {
        betNotInProg = DataContainer.dataFromDB.getQueryManager().getBetNotInProg(
                DataContainer.id);
        
        jTextFieldBetName.setText(betNotInProg.getBetName());

        String date = betNotInProg.getDate();
        selectData(date);
        
        jTextFieldOdd.setText(Double.toString(betNotInProg.getOdd()));
        jTextFieldStake.setText(Double.toString(betNotInProg.getStake()));
        
        String bukmacher = betNotInProg.getBukmacher();
        int index = selectBukmacher(bukmacher);
        jComboBoxBukmacher.setSelectedIndex(index);

        jTextAreaNote.setText(betNotInProg.getNote());
        
        String type = betNotInProg.getType();
        jComboBoxType.setSelectedItem(type.toLowerCase());
        
        status = betNotInProg.getBetStatus();
        selectStatus(status);       
    }
    
    private void loadDataFromDBforBetInProg()
    {
        betInProg = DataContainer.dataFromDB.getQueryManager().
                getBetInProgression(DataContainer.id);
        
        jTextFieldBetName.setText(betInProg.getBetName());

        String date = betInProg.getDate();
        selectData(date);
        
        jTextFieldOdd.setText(Double.toString(betInProg.getOdd()));
        jTextFieldStake.setText(Double.toString(betInProg.getStake()));
        
        String bukmacher = betInProg.getBukmacher();
        int index = selectBukmacher(bukmacher);
        jComboBoxBukmacher.setSelectedIndex(index);

        jTextAreaNote.setText(betInProg.getNote());
        
        String type = betInProg.getType();
        jComboBoxType.setSelectedItem(type.toLowerCase()); 
        
        status = betInProg.getBetStatus();
        selectStatus(status);
        
        //ustawienie kontrolek progresji
        jCheckBoxProgression.setSelected(true);
        jPanelProgression.setVisible(true);
        jRadioButtonExistingProgression.setSelected(true);      
        int progressionId = betInProg.getPartOfProgression(); 
        int progIndex = getProgressionIndex(progressionId);
              
        jComboBoxExistingProgression.setSelectedIndex(progIndex);
    }
    
    private int getProgressionIndex(int progressionId)
    {
        int progIndex = 0;
        for(int i=0; i<DataContainer.comboBoxModelAllProgressions.getSize(); i++)
        {
            Progression prog = (Progression) DataContainer.comboBoxModelAllProgressions.getElementAt(i);
            if(prog.getProgressionId() == progressionId)
                   progIndex = i;
        }
        return progIndex;
    }
    
    private void selectData(String date)
    {
        String year = calendar.getYear(date);
        String month = calendar.getMonth(date);
        String day = calendar.getDay(date);
        String hour = calendar.getHour(date);
        String minute = calendar.getMinute(date);
        
        for(int i=0; i < jComboBoxYear.getItemCount(); i++)
        {
            if(jComboBoxYear.getItemAt(i).toString().equals(year))
                jComboBoxYear.setSelectedIndex(i);
        }
        
        for(int i=0; i < jComboBoxMonth.getItemCount(); i++)
        {
            if(jComboBoxMonth.getItemAt(i).toString().equals(month))
                jComboBoxMonth.setSelectedIndex(i);
        }
        
        for(int i=0; i < jComboBoxDay.getItemCount(); i++)
        {
            if(jComboBoxDay.getItemAt(i).toString().equals(day))
                jComboBoxDay.setSelectedIndex(i);
        }
        
        for(int i=0; i < jComboBoxHour.getItemCount(); i++)
        {
            if(jComboBoxHour.getItemAt(i).toString().equals(hour))
                jComboBoxHour.setSelectedIndex(i);
        }
        
        for(int i=0; i <jComboBoxMinute.getItemCount(); i++)
        {
            if(jComboBoxMinute.getItemAt(i).toString().equals(minute))
                jComboBoxMinute.setSelectedIndex(i);
        }             
    }
    
    private void selectStatus(int status)
    {
        if(status == 1)
            jRadioButtonUnresolved.setSelected(true);
        
        if(status == 2)
            jRadioButtonWon.setSelected(true);
        
        if(status == 3)
            jRadioButtonLost.setSelected(true);
    }
    
   private int selectBukmacher(String bukmacher)
    {
        for(int i=0; i < jComboBoxBukmacher.getItemCount(); i++)
        {
            if(jComboBoxBukmacher.getItemAt(i).toString().equals(bukmacher))
                return i;
        }
        return -1;
    }   
   
   private int setProgressionStatus(int status)
   {
       int result = 0;
       
       if(status == 1 || status == 3)
           result = 1;
       
       if(status == 2)
           result = 2;
       
       return result;
   }
   
   private void viewProgressionBalanceInLabel()
   {
        Progression prog = (Progression) jComboBoxExistingProgression.getSelectedItem();
        String progressionBalance = DataContainer.dataFromDB.viewProgressionBallance(prog);
        jLabelProgressionBalance.setText(progressionBalance);
   }
    
    private void jButtonSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveChangesActionPerformed

        String betName = jTextFieldBetName.getText();
        String date = calendar.setDate();
        double odd = Double.parseDouble(jTextFieldOdd.getText());
        double stake = Double.parseDouble(jTextFieldStake.getText());
        String bukmacher = jComboBoxBukmacher.getSelectedItem().toString();
        String note = jTextAreaNote.getText();
        String type = jComboBoxType.getSelectedItem().toString();        
      
        
        //wylacznie autocommita
                try
                {
                    DataContainer.dataFromDB.getQueryManager().getConn().setAutoCommit(false);
                }
                catch(SQLException e)
                {
                    System.out.println("autocommit error");
                }
            

        if(jCheckBoxProgression.isSelected())
        {
            String progressionName = "";
            int progressionId = 0;

            if(jRadioButtonExistingProgression.isSelected())
            {             
                progressionName = jComboBoxExistingProgression.getSelectedItem().toString();
                progressionId = DataContainer.dataFromDB.
                        getProgressionsIndexById(jComboBoxExistingProgression.getSelectedIndex());
                
                //status progresji zalezy od statusu zakladu
                //status zakladu - 1 lub 3 -> status progresji = 1 (progresja trwa)
                //status zakladu - 1 lub 3 -> status progresji = 2 (progresja zakonczona)
                int progressionsStatus = setProgressionStatus(status);               

                //public BetInProgression(int betId, String betName, String date, double odd, 
                //double stake, int betStatus, String bukmacher, String note, double balance, 
                //String type, int progressionId, String progressionName, int progressionStatus)
                BetInProgression bip = new BetInProgression(DataContainer.id, betName, date, 
                        odd, stake, status, bukmacher, note, 0.0 , type, 
                        progressionId , progressionName, progressionsStatus);
                
                DataContainer.dataFromDB.getQueryManager().updateBet(bip);
            }

            if(jRadioButtonNewProgression.isSelected())
            {
                progressionName = jTextFieldProgressionName.getText();
                
                //dodaje progresje, zeby mozna bylo pobrac nowe id progresji dla zakladu
                DataContainer.dataFromDB.getQueryManager().addProgression(progressionName);
                progressionId = DataContainer.dataFromDB.getQueryManager().countAllProgressions(); 
                
                //public BetInProgression(int betId, String betName, String date, double odd, 
                //double stake, int betStatus, String bukmacher, String note, double balance, 
                //String type, int progressionId, String progressionName, int progressionStatus)
                BetInProgression bip = new BetInProgression(DataContainer.id, betName, date, 
                        odd, stake, status, bukmacher, note, 0.0 , type, 
                        progressionId , progressionName, 1);

                DataContainer.dataFromDB.getQueryManager().updateBet(bip);
                //DataContainer.dataFromDB.getQueryManager().addProgression(progressionName);
            }
        }
        else
        {           
            //tworzy nowy obiekt Bet, w którym balance nie jest zalezny od obiektu, tylko od statusu
            //id zakladu zostaje to samo, zmieniają sie tylko dane zakładu w bazie
            
            //public Bet(int betId, String betName, String date, double odd, double stake, int partOfProgression,
            //int betStatus, String bukmacher, String note, double balance, String type)
            Bet bet = new Bet(DataContainer.id, betName, date, odd, stake, 0, status,
                    bukmacher, note, 0.0, type);
         
            DataContainer.dataFromDB.getQueryManager().updateBet(bet);
        }
        
        //aktualizacja wszystkich list
        DataContainer.updateLists();
    }//GEN-LAST:event_jButtonSaveChangesActionPerformed
  
    private void jCheckBoxProgressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProgressionActionPerformed

        if(jCheckBoxProgression.isSelected())
            jPanelProgression.setVisible(true);
        else
            jPanelProgression.setVisible(false);
    }//GEN-LAST:event_jCheckBoxProgressionActionPerformed

    private void jRadioButtonNewProgressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNewProgressionActionPerformed

        if(jRadioButtonNewProgression.isSelected())
        {
            jTextFieldProgressionName.setEnabled(true);
            jComboBoxExistingProgression.setEnabled(false);
            jLabelProgressionBalance.setText("");
        }
        else
        {
            jTextFieldProgressionName.setEnabled(false);
            jComboBoxExistingProgression.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonNewProgressionActionPerformed

    private void jRadioButtonExistingProgressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonExistingProgressionActionPerformed

        if(jRadioButtonExistingProgression.isSelected())
        {
            jTextFieldProgressionName.setEnabled(false);
            jComboBoxExistingProgression.setEnabled(true);
            viewProgressionBalanceInLabel();
        }
        else
        {
            jTextFieldProgressionName.setEnabled(true);
            jComboBoxExistingProgression.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonExistingProgressionActionPerformed

    private void jRadioButtonWonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWonActionPerformed
        
        status = 2;
    }//GEN-LAST:event_jRadioButtonWonActionPerformed

    private void jRadioButtonLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLostActionPerformed
        
        status = 3;
    }//GEN-LAST:event_jRadioButtonLostActionPerformed

    private void jRadioButtonUnresolvedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUnresolvedActionPerformed
        
        status = 1;
    }//GEN-LAST:event_jRadioButtonUnresolvedActionPerformed

    private void jComboBoxExistingProgressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxExistingProgressionActionPerformed
        
        viewProgressionBalanceInLabel();
    }//GEN-LAST:event_jComboBoxExistingProgressionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupProgression;
    private javax.swing.ButtonGroup buttonGroupStatus;
    private javax.swing.JButton jButtonSaveChanges;
    private javax.swing.JCheckBox jCheckBoxProgression;
    private javax.swing.JComboBox jComboBoxBukmacher;
    private javax.swing.JComboBox jComboBoxDay;
    private javax.swing.JComboBox jComboBoxExistingProgression;
    private javax.swing.JComboBox jComboBoxHour;
    private javax.swing.JComboBox jComboBoxMinute;
    private javax.swing.JComboBox jComboBoxMonth;
    private javax.swing.JComboBox jComboBoxType;
    private javax.swing.JComboBox jComboBoxYear;
    private javax.swing.JLabel jLabelBetName;
    private javax.swing.JLabel jLabelBukmacher;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelNewProgressionName;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JLabel jLabelOdd;
    private javax.swing.JLabel jLabelProgressionBalance;
    private javax.swing.JLabel jLabelStake;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelType;
    private javax.swing.JPanel jPanelEditBet;
    private javax.swing.JPanel jPanelProgression;
    private javax.swing.JRadioButton jRadioButtonExistingProgression;
    private javax.swing.JRadioButton jRadioButtonLost;
    private javax.swing.JRadioButton jRadioButtonNewProgression;
    private javax.swing.JRadioButton jRadioButtonUnresolved;
    private javax.swing.JRadioButton jRadioButtonWon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaNote;
    private javax.swing.JTextField jTextFieldBetName;
    private javax.swing.JTextField jTextFieldOdd;
    private javax.swing.JTextField jTextFieldProgressionName;
    private javax.swing.JTextField jTextFieldStake;
    // End of variables declaration//GEN-END:variables
}
