/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package coverbooker;

import java.text.NumberFormat;

/**
 *
 * @author Marcin
 */
public class CoverBooker extends javax.swing.JPanel {

    CoverBookerCalc calc; 
    NumberFormat nf = NumberFormat.getInstance();
    CoverTypeENUM selectedType; 
    
    public CoverBooker() {
        initComponents();
        
        nf.setMaximumFractionDigits(2);
        nf.setMinimumFractionDigits(2);
        
        jRadioButtonHomeDraw.setText(CoverTypeENUM.Home_Draw.toString());
        jRadioButtonHomeAway.setText(CoverTypeENUM.Home_Away.toString());
        jRadioButtonDrawHome.setText(CoverTypeENUM.Draw_Home.toString());
        jRadioButtonDrawAway.setText(CoverTypeENUM.Draw_Away.toString());
        jRadioButtonAwayDraw.setText(CoverTypeENUM.Away_Draw.toString());
        jRadioButtonAwayHome.setText(CoverTypeENUM.Away_Home.toString());
        
        selectedType = CoverTypeENUM.Home_Draw;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCoverType = new javax.swing.ButtonGroup();
        jPanelCoverBooker = new javax.swing.JPanel();
        jTextFieldSecBetAmount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDrawPChance = new javax.swing.JTextField();
        jTextFieldDrawCourse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonCalculateMOney = new javax.swing.JButton();
        jRadioButtonDrawAway = new javax.swing.JRadioButton();
        jTextFieldAwayPChance = new javax.swing.JTextField();
        jRadioButtonAwayHome = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBestBet = new javax.swing.JTextField();
        jTextFieldCleanWin = new javax.swing.JTextField();
        jTextFieldHomeCourse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldMainBetAmount = new javax.swing.JTextField();
        jRadioButtonHomeAway = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCountPChance = new javax.swing.JButton();
        jLabelAwayHomePChance = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonDrawHome = new javax.swing.JRadioButton();
        jTextFieldMoneyBudget = new javax.swing.JTextField();
        jTextFieldPossibleWin = new javax.swing.JTextField();
        jTextFieldHomePChance = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonHomeDraw = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAwayCourse = new javax.swing.JTextField();
        jRadioButtonAwayDraw = new javax.swing.JRadioButton();
        jLabelHomeDrawPChance = new javax.swing.JLabel();
        jLabelHomeAwayPChance = new javax.swing.JLabel();
        jLabelDrawHomePChance = new javax.swing.JLabel();
        jLabelDrawAwayPChance = new javax.swing.JLabel();
        jLabelAwayDrawPChance = new javax.swing.JLabel();

        jTextFieldSecBetAmount.setEnabled(false);

        jLabel9.setText("Secondary bet amount:");

        jTextFieldDrawPChance.setText("Draw");
        jTextFieldDrawPChance.setEnabled(false);

        jLabel7.setText("Budget: ");

        jButtonCalculateMOney.setText("Calculate money for bet");
        jButtonCalculateMOney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateMOneyActionPerformed(evt);
            }
        });

        buttonGroupCoverType.add(jRadioButtonDrawAway);
        jRadioButtonDrawAway.setText("Draw_Away4");
        jRadioButtonDrawAway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDrawAwayActionPerformed(evt);
            }
        });

        jTextFieldAwayPChance.setText("Away");
        jTextFieldAwayPChance.setEnabled(false);

        buttonGroupCoverType.add(jRadioButtonAwayHome);
        jRadioButtonAwayHome.setText("Away_Home6");
        jRadioButtonAwayHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAwayHomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Home:");

        jTextFieldBestBet.setEnabled(false);

        jTextFieldCleanWin.setText("Clean win");
        jTextFieldCleanWin.setEnabled(false);

        jLabel10.setText("Choose cover type:");

        jTextFieldMainBetAmount.setEnabled(false);

        buttonGroupCoverType.add(jRadioButtonHomeAway);
        jRadioButtonHomeAway.setText("Home_Away2");
        jRadioButtonHomeAway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHomeAwayActionPerformed(evt);
            }
        });

        jLabel1.setText("Courses:");

        jLabel8.setText("Main bet amount:");

        jLabel5.setText("Percentage Chance:");

        jButtonCountPChance.setText("Percentage Chance");
        jButtonCountPChance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountPChanceActionPerformed(evt);
            }
        });

        jLabelAwayHomePChance.setText("-");

        jLabel6.setText("Best bet:");

        buttonGroupCoverType.add(jRadioButtonDrawHome);
        jRadioButtonDrawHome.setText("Draw_Home3");
        jRadioButtonDrawHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDrawHomeActionPerformed(evt);
            }
        });

        jTextFieldPossibleWin.setText("Possible win");
        jTextFieldPossibleWin.setEnabled(false);

        jTextFieldHomePChance.setText("Home");
        jTextFieldHomePChance.setEnabled(false);

        jLabel3.setText("Draw:");

        buttonGroupCoverType.add(jRadioButtonHomeDraw);
        jRadioButtonHomeDraw.setText("Home_Draw1");
        jRadioButtonHomeDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonHomeDrawActionPerformed(evt);
            }
        });

        jLabel4.setText("Away:");

        buttonGroupCoverType.add(jRadioButtonAwayDraw);
        jRadioButtonAwayDraw.setText("Away_Draw5");
        jRadioButtonAwayDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAwayDrawActionPerformed(evt);
            }
        });

        jLabelHomeDrawPChance.setText("-");

        jLabelHomeAwayPChance.setText("-");

        jLabelDrawHomePChance.setText("-");

        jLabelDrawAwayPChance.setText("-");

        jLabelAwayDrawPChance.setText("-");

        javax.swing.GroupLayout jPanelCoverBookerLayout = new javax.swing.GroupLayout(jPanelCoverBooker);
        jPanelCoverBooker.setLayout(jPanelCoverBookerLayout);
        jPanelCoverBookerLayout.setHorizontalGroup(
            jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                            .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldMoneyBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                .addComponent(jLabel1)
                                .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldDrawCourse))
                                        .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(10, 10, 10)
                                            .addComponent(jTextFieldHomeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldAwayCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jButtonCountPChance))
                            .addGap(71, 71, 71)
                            .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)
                                .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldDrawPChance, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldHomePChance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                        .addComponent(jTextFieldAwayPChance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel9)
                                .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldBestBet, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldSecBetAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(jTextFieldMainBetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                            .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRadioButtonDrawHome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonHomeDraw, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonAwayHome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonDrawAway, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonHomeAway, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonAwayDraw, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonCalculateMOney, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(46, 46, 46)
                            .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelAwayDrawPChance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAwayHomePChance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDrawAwayPChance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDrawHomePChance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelHomeAwayPChance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelHomeDrawPChance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                                    .addComponent(jTextFieldPossibleWin, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldCleanWin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(42, 42, 42)))
                    .addContainerGap()))
        );
        jPanelCoverBookerLayout.setVerticalGroup(
            jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
            .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCoverBookerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldHomeCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldHomePChance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldDrawCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDrawPChance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAwayCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAwayPChance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonCountPChance)
                        .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldBestBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(36, 36, 36)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTextFieldMoneyBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldMainBetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextFieldSecBetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonHomeDraw)
                        .addComponent(jLabelHomeDrawPChance))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelHomeAwayPChance)
                        .addComponent(jRadioButtonHomeAway, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonDrawHome)
                        .addComponent(jLabelDrawHomePChance))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDrawAwayPChance)
                        .addComponent(jRadioButtonDrawAway))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonAwayHome)
                        .addComponent(jLabelAwayHomePChance))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAwayDrawPChance)
                        .addComponent(jRadioButtonAwayDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(jPanelCoverBookerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCalculateMOney)
                        .addComponent(jTextFieldPossibleWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCleanWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCoverBooker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCoverBooker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalculateMOneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateMOneyActionPerformed

        double moneyBudget = Double.parseDouble(jTextFieldMoneyBudget.getText());
        //CoverTypeENUM bestType = calc.getBestType();

        double homeCourse = calc.getEvent().getHomeCourse();
        double drawCourse = calc.getEvent().getDrawCourse();
        double awayCourse = calc.getEvent().getAwayCourse();

        calc.getCoverBookerMoney().calcuteMoneyRates(homeCourse,
            drawCourse, awayCourse, moneyBudget, selectedType);

        double possibleWin = calc.getCoverBookerMoney().calculatePossibleWin(homeCourse,
            drawCourse, awayCourse, calc.getCoverBookerMoney().getMainBetMoney(),
            selectedType);

        double cleanWin = calc.getCoverBookerMoney().calculateCleanWin(possibleWin, moneyBudget);

        String mainBetMoneyString = nf.format(calc.getCoverBookerMoney().getMainBetMoney());
        String secBetMoneyString = nf.format(calc.getCoverBookerMoney().getSecondaryBetMoney());
        String possibleWinString = nf.format(possibleWin);
        String cleanWinString = nf.format(cleanWin);

        jTextFieldMainBetAmount.setText(mainBetMoneyString);
        jTextFieldSecBetAmount.setText(secBetMoneyString);
        jTextFieldPossibleWin.setText(possibleWinString);
        jTextFieldCleanWin.setText(cleanWinString);
    }//GEN-LAST:event_jButtonCalculateMOneyActionPerformed

    private void jRadioButtonDrawAwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDrawAwayActionPerformed

        selectedType = CoverTypeENUM.Draw_Away;
    }//GEN-LAST:event_jRadioButtonDrawAwayActionPerformed

    private void jRadioButtonAwayHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAwayHomeActionPerformed

        selectedType = CoverTypeENUM.Away_Home;
    }//GEN-LAST:event_jRadioButtonAwayHomeActionPerformed

    private void jRadioButtonHomeAwayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHomeAwayActionPerformed

        selectedType = CoverTypeENUM.Home_Away;
    }//GEN-LAST:event_jRadioButtonHomeAwayActionPerformed

    private void jButtonCountPChanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountPChanceActionPerformed

        calc = new CoverBookerCalc(jTextFieldHomeCourse, 
                jTextFieldDrawCourse, jTextFieldAwayCourse);
        calc.calculatePercentageChance();

        double homePChance = calc.getpChance().getHomePercentageChance();
        double drawPChance = calc.getpChance().getDrawPercentageChance();
        double awayPChance = calc.getpChance().getAwayPercentageChance();

        calc.getBestOptionSorter();
        CoverTypeENUM bestType = calc.getBestType();

        String homePChanceString = nf.format(homePChance);
        String drawPChanceString = nf.format(drawPChance);
        String awayPChanceString = nf.format(awayPChance);

        String homeAndDrawPChanceString = nf.format(calc.getpChance().getHomeAndDrawPChance());
        String homeAndAwayPChanceString = nf.format(calc.getpChance().getHomeAndAwayPChance());
        String drawAndAwayPChanceString = nf.format(calc.getpChance().getDrawAndAwayPChance());

        jTextFieldHomePChance.setText(homePChanceString);
        jTextFieldDrawPChance.setText(drawPChanceString);
        jTextFieldAwayPChance.setText(awayPChanceString);
        jTextFieldBestBet.setText(bestType.toString());

        jLabelHomeDrawPChance.setText(homeAndDrawPChanceString);
        jLabelDrawHomePChance.setText(homeAndDrawPChanceString);
        jLabelHomeAwayPChance.setText(homeAndAwayPChanceString);
        jLabelAwayHomePChance.setText(homeAndAwayPChanceString);
        jLabelDrawAwayPChance.setText(drawAndAwayPChanceString);
        jLabelAwayDrawPChance.setText(drawAndAwayPChanceString);
    }//GEN-LAST:event_jButtonCountPChanceActionPerformed

    private void jRadioButtonDrawHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDrawHomeActionPerformed

        selectedType = CoverTypeENUM.Draw_Home;
    }//GEN-LAST:event_jRadioButtonDrawHomeActionPerformed

    private void jRadioButtonHomeDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonHomeDrawActionPerformed

        selectedType = CoverTypeENUM.Home_Draw;
    }//GEN-LAST:event_jRadioButtonHomeDrawActionPerformed

    private void jRadioButtonAwayDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAwayDrawActionPerformed

        selectedType = CoverTypeENUM.Away_Draw;
    }//GEN-LAST:event_jRadioButtonAwayDrawActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCoverType;
    private javax.swing.JButton jButtonCalculateMOney;
    private javax.swing.JButton jButtonCountPChance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAwayDrawPChance;
    private javax.swing.JLabel jLabelAwayHomePChance;
    private javax.swing.JLabel jLabelDrawAwayPChance;
    private javax.swing.JLabel jLabelDrawHomePChance;
    private javax.swing.JLabel jLabelHomeAwayPChance;
    private javax.swing.JLabel jLabelHomeDrawPChance;
    private javax.swing.JPanel jPanelCoverBooker;
    private javax.swing.JRadioButton jRadioButtonAwayDraw;
    private javax.swing.JRadioButton jRadioButtonAwayHome;
    private javax.swing.JRadioButton jRadioButtonDrawAway;
    private javax.swing.JRadioButton jRadioButtonDrawHome;
    private javax.swing.JRadioButton jRadioButtonHomeAway;
    private javax.swing.JRadioButton jRadioButtonHomeDraw;
    private javax.swing.JTextField jTextFieldAwayCourse;
    private javax.swing.JTextField jTextFieldAwayPChance;
    private javax.swing.JTextField jTextFieldBestBet;
    private javax.swing.JTextField jTextFieldCleanWin;
    private javax.swing.JTextField jTextFieldDrawCourse;
    private javax.swing.JTextField jTextFieldDrawPChance;
    private javax.swing.JTextField jTextFieldHomeCourse;
    private javax.swing.JTextField jTextFieldHomePChance;
    private javax.swing.JTextField jTextFieldMainBetAmount;
    private javax.swing.JTextField jTextFieldMoneyBudget;
    private javax.swing.JTextField jTextFieldPossibleWin;
    private javax.swing.JTextField jTextFieldSecBetAmount;
    // End of variables declaration//GEN-END:variables
}
